### PR TITLE
exclude node_modules from babel-loader

### PR DESCRIPTION
**Pull request by pocketjoso**
slows down code bundling significantly to apply to all node_modules,
which shouldn't be done (they should be transpiled before published)

@Ledoux Can you merge and publish new version? Thanks!

### CODE REVIEW

**Comment by pocketjoso** [comment]
@Ledoux Rebased the PR. Also made mirror PR for angular: https://github.com/snipsco/teleport-webpack-angular/pull/2

**Review by Ledoux — APPROVED** [review]

**Comment by Ledoux** [comment]
@pocketjoso 
apparently I have no more the right to merge... I think I am not anymore admin in each teleport repo since Yann removed me fro the team :(.
Could you please re add me manually in each repo, please ?
https://github.com/snipsco/teleport
https://github.com/snipsco/teleport-webpack-react
https://github.com/snipsco/teleport-webpack-angular
https://github.com/snipsco/teleport-express-webrouter
https://github.com/snipsco/teleport-flask-webrouter
https://github.com/snipsco/teleport-flask-websocket

**Comment by pocketjoso** [comment]
@Ledoux Invited you to all them.

**Comment by pocketjoso** [comment]
@Ledoux ping!

**Comment by pocketjoso** [comment]
@Ledoux Merged - you should publish a `patch` to npm so users can get this change.

**Pull request merged**
